### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by XiaChaoStudio** [Schlampig/OpenNRE_for_Chinese#1]
Traceback (most recent call last):
  File "./learn.py", line 42, in <module>
    is_training=True)
  File "./learn.py", line 29, in learn
    con.train()
  File "/home/xiachao/workspace/OpenNRE_for_Chinese-master/config.py", line 251, in train
    loss = self.train_one_step()
  File "/home/xiachao/workspace/OpenNRE_for_Chinese-master/config.py", line 224, in train_one_step
    self.acc_not_NA.add(prediction == self.batch_label[i])
TypeError: eq() received an invalid combination of arguments - got (numpy.int64), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (numpy.int64)
 * (Number other)
      didn't match because some of the arguments have invalid types: (numpy.int64)

How to solve this problem？

**Comment by Schlampig** [comment]
> TypeError: eq() received an invalid combination of arguments



> Traceback (most recent call last):
> File "./learn.py", line 42, in 
> is_training=True)
> File "./learn.py", line 29, in learn
> con.train()
> File "/home/xiachao/workspace/OpenNRE_for_Chinese-master/config.py", line 251, in train
> loss = self.train_one_step()
> File "/home/xiachao/workspace/OpenNRE_for_Chinese-master/config.py", line 224, in train_one_step
> self.acc_not_NA.add(prediction == self.batch_label[i])
> TypeError: eq() received an invalid combination of arguments - got (numpy.int64), but expected one of:
> 
> * (Tensor other)
>   didn't match because some of the arguments have invalid types: (numpy.int64)
> * (Number other)
>   didn't match because some of the arguments have invalid types: (numpy.int64)
> 
> How to solve this problem？

The error implies that in line 224 of the file config.py, the equation operation requires the compared arguments in either integer or torch.tensor format. However the argument is numpy.int64.  

You could try to check whether your label index is in correct format, using  integer rather than numpy.array.

another ref: 
https://stackoverflow.com/questions/54999926/pytorch-typeerror-eq-received-an-invalid-combination-of-arguments
